image: frankh/arachnys-gitlab-runner:v0.0.3

services:
  - docker:dind

variables:
  CI_SHORT_COMMIT_SHA: "$${CI_COMMIT_SHA:0:8}"
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

before_script:
  - /entrypoint.sh true
  # Hack to get short commit hash
  - eval export VERSION=${CI_SHORT_COMMIT_SHA}
  - eval export QA_DEPLOY_URL=rocketboard-${CI_COMMIT_REF_SLUG}-qa.k8s-dev.arachnys.com
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - test
  - publish
  - deploy

build_backend:
  stage: build
  script:
    - VERSION=${VERSION} make build

build_frontend:
  stage: build
  script:
    - VERSION=${VERSION} make build/frontend

test_backend:
  stage: test
  script:
    - make test

test_frontend:
  stage: test
  script:
    - make test/ci
  artifacts:
    paths:
      - uda.zip
    expire_in: 1 week

publish:
  stage: publish
  script:
    - VERSION=${VERSION} make publish

deploy_qa:
  stage: deploy
  script:
    - vault read -field=kubeconfig.k8s-dev secret/jenkins > .kubeconfig
    - VERSION=${VERSION} KUBECONFIG=./.kubeconfig.k8s-dev make deploy/qa
  environment:
    name: qa/$CI_COMMIT_REF_NAME
    # We cannot use `QA_DEPLOY_URL` here.
    # See https://gitlab.com/gitlab-org/gitlab-ce/issues/27921
    url: https://rocketboard-${CI_COMMIT_REF_SLUG}-qa.k8s-dev.arachnys.com
  except:
    - master

