apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rocketboard.fullname" . }}
  labels:
    app: {{ template "rocketboard.name" . }}
    chart: {{ template "rocketboard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rocketboard.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "rocketboard.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: arachnys-docker
{{- if index .Values.persistence.enabled }}
      volumes:
        - name: rocketboard-data
          persistentVolumeClaim:
            claimName: {{ template "rocketboard.fullname" . }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if index .Values.persistence.enabled }}
          volumeMounts:
          - mountPath: "/data"
            name: rocketboard-data
{{- end }}
          env:
            - name: ROCKET_DATA_DIR
              value: /data
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
