kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ template "rocketboard.name" . }}
    chart: {{ template "rocketboard.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "rocketboard.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
