replicaCount: 1

image:
  repository: docker.arachnys.com/rocketboard
  tag: stable
  pullPolicy: IfNotPresent

include-qa-annotations: true

ingress:
  enabled: true
  path: /
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$request_uri"
  hosts:
    - rocketboard.arachnys.com
  tls:
    - secretName: arachnys-wildcard-tls
      hosts:
        - rocketboard.arachnys.com

oauth2-proxy:
  replicaCount: 1

  image:
    tag: "2.2.1-alpha"

  service:
    port: 4180

  ingress:
    enabled: true
    path: /oauth2
    hosts:
      - rocketboard.arachnys.com
    tls:
      - secretName: arachnys-wildcard-tls
        hosts:
          - rocketboard.arachnys.com

  config:
    clientID: ***REMOVED***
    clientSecret: ***REMOVED***
    cookieSecret: ***REMOVED***
    htpasswdFile: |
      rocketboard:***REMOVED***

  extraArgs:
    oidc-issuer-url: "https://oauth.k8s-dev.arachnys.com"
    provider: "oidc"
    upstream: "http://rocketboard"
    http-address: "0.0.0.0:4180"

resources: {}
